### PR TITLE
Refactor contents listing

### PR DESCRIPTION
**Pull request by DenisaCG**
Refactored the listing of contents in the `get` function by extracting the content at that directory level and displaying it. Adapted the `delete` and `copy` functionalities to work the same way - in order to eliminate corner cases brought by different file paths.

### CODE REVIEW

**Comment by DenisaCG** [comment]
Do you want to take a look and test it locally with your bucket before we merge it? Thanks! @trungleduc

**Comment by trungleduc** [comment]
Thanks! I will take a look

**Review by trungleduc — APPROVED** [review]

**Comment by trungleduc** [comment]
it works great! Thanks @DenisaCG

**Comment by DenisaCG** [comment]
Great, thanks for testing it! @trungleduc

**Pull request merged**
